misat:	SAT-alumnes.cpp
	g++ -O3 -Wall SAT-alumnes.cpp -o misat

misat_cpy: SAT-cpy.cpp
	g++ -O3 -Wall SAT-cpy.cpp -o misat_cpy

misat-v1: SAT-v1.cpp 
	g++ -O3 -Wall SAT-v1.cpp -o misat-v1

misat-v2: SAT-v2.cpp 
	g++ -O3 -Wall SAT-v2.cpp -o misat-v2